# -*- coding: utf-8 -*-
"""Интернет-магазин_ПК_Осипов_Вадим.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqUeNUF1bi9OzvyQkfe9dzllJ2xzQlxt
"""

# Подгрузим необходимые библиотеки

import pandas as pd
import numpy as np
from google.colab import files
import re
import matplotlib.pyplot as plt
import seaborn as sns
import json
import scipy
import scipy.stats as stats
import sklearn.linear_model as lm

import warnings
warnings.filterwarnings('ignore')

#/content/sample_data/final_task.csv
#/content/drive/MyDrive/Colab Notebooks/0_Portfolio/1. Интернет_магазин _по _продаже_ПК/final_task.csv

from google.colab import drive
drive.mount('/content/drive')

# Загрузим данные в блокнот
#files.upload()

"""# 1. Предобработка данных"""

# Откроем наш загруженный датафрейм и присвоим ему имя df
#df = pd.read_csv('/content/final_task.csv')
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/0_Portfolio/1. Интернет_магазин _по _продаже_ПК/final_task.csv')



"""Выведем на экран первые три наблюдения датафрейма"""

# Ознакомимся с записями датафрейма
df.head(3)

# Размеры датафрейма
df.shape

# Информация по датафрейму
df.info()

"""* Целевая переменная price имеет строковый тип данных!
* наблюдаем, что только один фактор имеет вещественное число - seller_rating.
* product_id - имеет int64, но для анализа это не существенно

Процент пропусков датасета
"""

# Процент пропусков
df.isna().sum()/df.shape[0]*100

"""Целевая переменная price имеет один пропуск или 0,022222 %, который мы впоследствии просто удалим!

Основные статистики датасета
"""

df.describe() # Статистики Датафрейма

"""На этом этапе - малоинформативны статистики"""

# Изучим датафрейм на количество дубликатов
df.duplicated().sum()

# Удалим их из нашего анализа

df = df.drop_duplicates()

# Проверяем размер после удаления строк
df.shape

# Поработаем с целевой переменной price, которая имеет строковый тип и одно осутствующее значение

df['price'][:10]

# Посмотрим тип признака price
df['price'].dtypes

# Изменим тип на строковый
df['price'] = df['price'].astype(str)

# Создадим функцию - убирающую лишние символы из значений price
def clear_price(price):
  return re.sub('\D', '', price)

#re.sub(r'[^\d.]', '', price.replace(',', '.'))

# Создадим новый столбец в нашем датафрейме с названием 'Очищенная цена'
df['Очищенная цена'] = df['price'].apply(clear_price)

df.columns

# Определим индекс строки с пустым названием
df[df['Очищенная цена'] == '']

# # Удалим эту строку
df.drop(1916, inplace= True)

df.shape

# Изменим на числовой тип
df['Очищенная цена'] = df['Очищенная цена'].astype('Int64')

df.info()

# Исправим индексы
df.reset_index(drop=True, inplace=True)

#df.info()

"""# 1.1 Поработаем с колонками"""

df.sample(5)

df.columns

# Видим, что колонки Процессор, Оперативная память, Жесткий диск,
# Габариты товара, Габариты товара (с упаковкой) - имеют JSON-строки.

# Оперативная память

df['Оперативная память'].isna().sum()

eval(df['Оперативная память'][0])

df['Тип_памяти'] = df['Оперативная память'].apply(lambda x: eval(x)['Тип оперативной памяти'])

df['Объем_памяти'] = df['Оперативная память'].apply(lambda x: eval(x)['Объем оперативной памяти (Гб)'])

df.head(3)

# Жесткий диск

eval(df['Жесткий диск'][0])

df['HDD'] = df['Жесткий диск'].apply(lambda x: eval(x)['Объем накопителя HDD'])

df['SSD'] = df['Жесткий диск'].apply(lambda x: eval(x)['Объем накопителя SSD'])

df.head(3)

# Процессор

eval(df['Процессор'][0])

df['Тип_процессора'] = df['Процессор'].apply(lambda x: eval(x)['Процессор_тип'])

df['Ядра'] = df['Процессор'].apply(lambda x: eval(x)['Количество ядер процессора'])

df.head(3)

# Посмотрим остальные колонки - на предмет их адекватности для анализа

df.columns

# Определим рабочие для анализа колонки (признаки).

col = ['Страна производства', 'title', 'sales', 'seller_rating', 'Операционная система', 'Тип_процессора',  'Тип_памяти', 'Объем_памяти',
       'Видеопроцессор', 'Ядра', 'HDD', 'SSD', 'Очищенная цена']

df = df[col]

df.head(3)

df.shape

# Переименуем колонки датафрейма
df.rename(columns= {'Страна производства': 'Country', 'title': 'title', 'sales': 'sales', 'Операционная система': 'OS', 'Тип_процессора': 'Processor',
                   'Тип_памяти': 'TypeMemory', 'Объем_памяти': 'VolumeMemory', 'Видеопроцессор': 'VideoCard', 'Ядра': 'Cores',
                   'Очищенная цена': 'Price'}, inplace= True)

df[:3]

#df.info()

# VolumeMemory

df['VolumeMemory'].value_counts(dropna= False)

# Как видим выше - величины объема памяти представлены сумбурно!

df['VolumeMemory'].isna().sum()

# Заменим пропущенные значения на 8 (8 Гб - средняя оперативная память)

df['VolumeMemory'].fillna(8, inplace= True)

df['VolumeMemory'].value_counts(dropna= False)

# Создадим функцию по очистке значений
def clean(data):
  return re.sub('\D', '', data)

# Переведем колонку в строковый тип
df['VolumeMemory'] =  df['VolumeMemory'].astype(str)

# Очистим колонку
df['VolumeMemory'] = df['VolumeMemory'].apply(clean)

df['VolumeMemory'].value_counts()

# Переведем колонку в числовой тип
df['VolumeMemory'] =  df['VolumeMemory'].astype(int)

df['VolumeMemory'].dtype

# Поработаем с выбросами (240 Гб, 1000 Гб)
df[df['VolumeMemory'] == (240)]

df[df['VolumeMemory'] == (1000)]

# Удалим их
df.drop([730, 3102], inplace= True)

# Проверяем размер
df.shape

# Cores

df['Cores'].value_counts(dropna= False)

df['Cores'].dtype

# С помощью функции очистим значения
df['Cores'] = df['Cores'].apply(clean)

# Посмотрим пустые значения
df[df['Cores'] == '']

# Исходя из выведенной таблицы выше - помимо ядер, - также являются не заполненными и многие другие, нам необходимые для анализа поля.
# Удалим эти поля

df = df[df['Cores'] != '']

df.shape

# Приведем к числовому типу
df['Cores'] = df['Cores'].astype(int)

df.head(3)

# HDD

df['HDD'] = df['HDD'].astype(str)

df['HDD'].dtypes

# Почистим значения
df['HDD'] = df['HDD'].apply(clean)

df[df['HDD'] == '']

df['HDD'].value_counts()

# Изменим тип на числовой
df['HDD'] = pd.to_numeric(df['HDD']).astype('Int64')

df['HDD'].value_counts(dropna= False)

# Посмотрим на выбросы
df[df['HDD'] == 40004000]

# Изменим величину в этом наблюдении:
df.at[3045, 'HDD'] = 4000

df[df['HDD'] == 500500]

df.at[3059, 'HDD'] = 500

df['HDD'].value_counts(dropna=False)

df['HDD'].describe()

# Аналогично произведем с SSD

df['SSD'] = df['SSD'].astype(str)

df['SSD'] = df['SSD'].apply(clean)

# Изменим тип на числовой
df['SSD'] = pd.to_numeric(df['SSD']).astype('Int64')

df['SSD'].value_counts(dropna= False)

# В этом признаке очень много выбросов, очевидно опечаток.
# Посмотрим эти наблюдения
df[df['SSD'] > 2000]

# Исправим
df.at[971, 'SSD'] = 512
df.at[1668, 'SSD'] = 512
df.at[2148, 'SSD'] = 512
df.at[3028, 'SSD'] = 240
df.at[3059, 'SSD'] = 128
df.at[3691, 'SSD'] = 960
df.at[3692, 'SSD'] = 960
df.at[3693, 'SSD'] = 960
df.at[3694, 'SSD'] = 960
df.at[3695, 'SSD'] = 960
df.at[3696, 'SSD'] = 960
df.at[3742, 'SSD'] = 960
df.at[3958, 'SSD'] = 960
df.at[3984, 'SSD'] = 480

# Посмотрим на значения в этом признаке
df['SSD'].value_counts(dropna= False)

# Почистим индексы
df.reset_index(drop=True, inplace= True)

df.info()

# Предварительный этап по очистке данных завершен:
# У меня получилось 13 признаков:
# 7 строковых, категориальных: Country, OS, Processor, TypeMemory, VideoCard, title, sales;
# 1 категориальный с вещественным значением (float64) - seller_rating (ранговая переменная);
# 5 с числовым значением (int64), такие как: VolumeMemory, Cores, HDD, SSD, Price (целевая переменная).

"""# 2. Разведочный анализ"""

df_eda = df.copy()

df_eda.sample(5)

# Посмотрим размер таблицы
df_eda.shape

df_eda.info()

"""Признаки, которые будут использованы для дальнейшего анализа:

***Количественные признаки:***

1.   Price (целевая переменная)
2.   VolumeMemory
3.   Cores
4.   HDD
5.   SSD


***Категориальные признаки:***
1.   Country
2.   seller_rating
3.   OS
4.   Processor
5.   TypeMemory
6.   VideoCard
7.   sales
8.   title

# 2.1 Неграфический и графический анализ количественных признаков

Price
"""

# Price

price = df_eda['Price']

# Рассчитаем максимальное и минимальное значение признака price
max_value = price.max()
min_value = price.min()
print('Наибольшая цена: ', max_value, 'Наименьшая цена: ', min_value)

# Посмотрим наблюдение с такой ценой
df_eda[df_eda['Price'] == 2418]

# Данные некорректны - удаляем это наблюдение
df_eda.drop(340, inplace= True)

df_eda['Price'].min()

df_eda[df_eda['Price'] == 2793]

# Это наблюдение также некорректно, удаляем его
df_eda.drop(341, inplace= True)

df_eda.shape

# Приведем в порядок индексы
df_eda.reset_index(drop= True, inplace= True)

#df_eda.info()

price = df_eda['Price']

# Рассчитаем заново максимальное и минимальное значение признака price
max_value = price.max()
min_value = price.min()
print('Наибольшая цена: ', max_value, 'Наименьшая цена: ', min_value)

# Посмотрим, номенклатуру - по этой цене
df_eda[df_eda['Price'] == 5672]

# Как видим выше - это мини ПК: пока оставим, далее когда будем анализировать title (наименование товара) - удалим такие элементы из этого признака.

# Медиана и средняя величина признака price
median_value = price.median()
mean_value = price.mean()
print('Медиана: ', median_value, 'Средняя цена: ', mean_value)

# медиана и средняя имеют отличия - это говорит о том, что имеются выбросы

# Рассчитаем процентили (10, 25, 50, 75, 90, 95, 99) с помощью метода quantile()
percentile_10_value = price.quantile(0.10)
percentile_25_value = price.quantile(0.25)
percentile_50_value = price.quantile(0.50)
percentile_75_value = price.quantile(0.75)
percentile_90_value = price.quantile(0.90)
percentile_95_value = price.quantile(0.95)
percentile_99_value = price.quantile(0.99)

print('10-й процентиль цены: ', percentile_10_value)
print('25-й процентиль цены: ', percentile_25_value)
print('50-й процентиль цены: ', percentile_50_value)
print('75-й процентиль цены: ', percentile_75_value)
print('90-й процентиль цены: ', percentile_90_value.round())
print('95-й процентиль цены: ', percentile_95_value.round())
print('99-й процентиль цены: ', percentile_99_value.round())

# Статистики признака price
price.describe().round()

#plt.style.available

plt.style.use(['seaborn-v0_8-deep'])

# Построим диаграмму "ящик с усами" признака price
plt.boxplot(price)
plt.show()

# Диаграмма показывает наличие выбросов - начиная с отметки 150 000 рублей.
# То есть, - эти значения лежат за пределами 1,5 межквартильного размаха основного массива величин

# Посмотрим на гистограмму признака price
price.hist(bins= 100)

price.hist(bins= 8)

"""Распределение не нормальное, левосимметричное, медиана - 66405

"""

# Проверим наше предположение с помощью асимметрии и эксцесса.
print(price.skew())
print(price.kurtosis())

# Метод skew() показывает на левостороннее смещение значений относительно ее моды (положительное значение).
# Эксцесс положительный, - плосковершинная форма графика относительно остроты пика нормального распределния признака.

df_eda.columns

"""Сводка по цене"""

# Наибольшая цена:  235900
# Наименьшая цена:  5672
# Медиана:  66405.0
# Средняя цена:  67061.6
# Асиметрия 0.9037131930041654
# Эксцесс 1.3707722100509625

"""VolumeMemory"""

# VolumeMemory

vm = df_eda['VolumeMemory']

# Рассчитаем максимальное и минимальное значение признака VolumeMemory, в Гб
max_value = vm.max()
min_value = vm.min()
print('Наибольший объем памяти: ', max_value, 'Наименьший объем памяти: ', min_value)

# Медиана и среднее значение объема памяти
median_value = vm.median()
mean_value = vm.mean()
print('Медиана объема памяти: ', median_value, 'Средний объем памяти: ', mean_value.round())

# Рассчитаем процентили (10, 25, 50, 75, 90) с помощью метода quantile()
percentile_10_value = vm.quantile(0.10)
percentile_25_value = vm.quantile(0.25)
percentile_50_value = vm.quantile(0.50)
percentile_75_value = vm.quantile(0.75)
percentile_90_value = vm.quantile(0.90)

print('10-й процентиль объема памяти: ', percentile_10_value)
print('25-й процентиль объема памяти: ', percentile_25_value)
print('50-й процентиль объема памяти: ', percentile_50_value)
print('75-й процентиль объема памяти: ', percentile_75_value)
print('90-й процентиль объема памяти: ', percentile_90_value.round())

# Ввиду того, что количество различных значений памяти невелико - отсюда и совпадение значений по квартилям

# Статистики признака VolumeMemory
vm.describe().round(1)

# Построим диаграмму "ящик с усами" признака vm
plt.boxplot(vm)
plt.show()

# Показывает, что межквартильный размах с медианой лежат в одном секторе.

# Посмотрим на гистограмму признака vm
vm.hist()

# Создадим круговую диаграмму
plt.figure(figsize= (7, 7))
g = vm.value_counts()[:5]
colors = sns.color_palette('pastel')[0:5]
plt.pie(g, labels= g.index, colors= colors, autopct='%.1f', );

# Посмотрим цены по ПК имеющим такие карты памяти:
df_eda.groupby('VolumeMemory')['Price'].agg(['mean', 'median']).round(1)

# Распределение объема памяти:
# 16 Гб - 58,1 %, 66732 рубля;
# 32 Гб - 19,4%, 96664 рубля;
# 8 Гб - 17,1%, 43312 рубля;
# 4 Гб - 3,6%, 26503 рубля
# 64 Гб - 1,9%, - 77044 рубля.

"""Сводка по признаку VolumeMemory"""

# Наибольший объем памяти:  64 - цена 77044 рубля;
# Наименьший объем памяти:  1 - цена 20000 рублей;
# Медиана объема памяти:  16.0
# Средний объем памяти:  18.0

"""Cores (количество ядер)"""

# Cores

cores = df_eda['Cores']

# Рассчитаем максимальное и минимальное значение признака Cores
max_value = cores.max()
min_value = cores.min()
print('Наибольшее количество ядер: ', max_value, 'Наименьшее количество ядер: ', min_value)

# Медиана и среднее значение количества ядер
median_value = cores.median()
mean_value = cores.mean()
print('Медиана : ', median_value, 'Среднее количество ядер: ', mean_value.round(1))

# Рассчитаем процентили (10, 25, 50, 75, 90) с помощью метода quantile()
percentile_10_value = cores.quantile(0.10)
percentile_25_value = cores.quantile(0.25)
percentile_50_value = cores.quantile(0.50)
percentile_75_value = cores.quantile(0.75)
percentile_90_value = cores.quantile(0.90)

print('10-й процентиль объема памяти: ', percentile_10_value)
print('25-й процентиль объема памяти: ', percentile_25_value)
print('50-й процентиль объема памяти: ', percentile_50_value)
print('75-й процентиль объема памяти: ', percentile_75_value)
print('90-й процентиль объема памяти: ', percentile_90_value.round())

cores.describe().round(1)

# Построим диаграмму "ящик с усами" признака cores
plt.boxplot(cores)
plt.show()

# Ввиду того, что средняя и медиана близки - выбросы на диаграмме не существенны, ввиду их малого количества (три);

# Построим гистограмму
cores.hist()

# Сводка по ценам:
df_eda.groupby('Cores')['Price'].agg(['mean', 'median']).round(1)

"""Cводка признака Cores"""

# Наибольшее количество ядер:  24 - цена ПК с такими ядрами 43417 рублей;
# Наименьшее количество ядер:  1 - цена 18001 рубля;
# Медиана :  6.0
# Среднее количество ядер:  7.0

"""HDD"""

# HDD

hdd = df_eda['HDD']

# Рассчитаем максимальное и минимальное значение признака HDD, в Гб
max_value = hdd.max()
min_value = hdd.min()
print('Наибольший объем памяти: ', max_value, 'Наименьший объем памяти: ', min_value)

# Медиана и среднее значение емкости жесткого носителя
median_value = hdd.median()
mean_value = hdd.mean()
print('Медиана : ', median_value, 'Средняя емкость носителя: ', mean_value.round(1))

# Средняя величина меньше медианы!

# Рассчитаем процентили (10, 25, 50, 75, 90) с помощью метода quantile()
percentile_10_value = hdd.quantile(0.10)
percentile_25_value = hdd.quantile(0.25)
percentile_50_value = hdd.quantile(0.50)
percentile_75_value = hdd.quantile(0.75)
percentile_90_value = hdd.quantile(0.90)

print('10-й процентиль объема памяти: ', percentile_10_value)
print('25-й процентиль объема памяти: ', percentile_25_value)
print('50-й процентиль объема памяти: ', percentile_50_value)
print('75-й процентиль объема памяти: ', percentile_75_value)
print('90-й процентиль объема памяти: ', percentile_90_value.round())

hdd.describe().round(1)

# Боксплот строить смысла нет, - все основные процентили лежет в одном значении - 1000

# Построим гистограмму
hdd.hist(bins= 8)

# Большинство значений расположено в значении 1000, поэтому средняя меньше медианы!

print(hdd.skew())
print(hdd.kurtosis())

# Отрицательная асимметрия говорит о том, что у нас правосторонняя асимметрия (правый хвост превалирует).
# Положительный эксцесс - говорит о плосковершинности пикового значения от нормального распределения,
# это и показывает неграфический способ (большинство значений это - 1000)

# Цена с такими накопителями:
df_eda.groupby('HDD')['Price'].agg(['mean', 'median']).round(1)

"""Сводка HDD"""

# Сводка HDD
# Наибольший объем памяти:  4000, цена с таким накопителем по ПК - 122490 рублей;
# Наименьший объем памяти:  0, цена с такими накопителями - 15460 рублей;
# Медиана :  1000.0, цена 77422 рубля;
# Средняя емкость носителя:  869.3
# Асимметрия = -0,14648
# Эксцесс = 6,42448

df_eda.shape

df_eda['HDD'].describe()

# Подводя итоги по признаку HDD:
# Можно сделать вывод о не состоятельности этого
# признака влиять существенно на итог анализа, ввиду того,
# что количество наблюдений 1143 из 3561

"""SSD"""

# SSD

ssd = df_eda['SSD']

# Рассчитаем максимальное и минимальное значение признака SSD, в Гб
max_value = ssd.max()
min_value = ssd.min()
print('Наибольший объем памяти: ', max_value, 'Наименьший объем памяти: ', min_value)

# Медиана и среднее значение емкости жесткого носителя
median_value = ssd.median()
mean_value = ssd.mean()
print('Медиана : ', median_value, 'Средняя емкость носителя: ', mean_value.round(1))

# Средняя больше медианы - имеются выбросы

# Рассчитаем процентили (10, 25, 50, 75, 90) с помощью метода quantile()
percentile_10_value = ssd.quantile(0.10)
percentile_25_value = ssd.quantile(0.25)
percentile_50_value = ssd.quantile(0.50)
percentile_75_value = ssd.quantile(0.75)
percentile_90_value = ssd.quantile(0.90)

print('10-й процентиль объема памяти: ', percentile_10_value)
print('25-й процентиль объема памяти: ', percentile_25_value)
print('50-й процентиль объема памяти: ', percentile_50_value)
print('75-й процентиль объема памяти: ', percentile_75_value)
print('90-й процентиль объема памяти: ', percentile_90_value.round())

# Статистики признака SSD
df_eda['SSD'].describe().round(1)

# Посмотрим значения признака SSD
df_eda['SSD'].value_counts(dropna= False)

# Удалим из признака SSD пустые значения
t = df_eda['SSD'].dropna()

# Построим боксплот по признаку SSD
plt.boxplot(t)
plt.show()

# График не выявляет выбросов, судя по МКР - данные представлены достаточно широко, средняя 545 Гб,
# медиана - 480 Гб.

t.hist()

print(t.skew())
print(t.kurtosis())

# Левосторонняя аимметрия
# Плосковершинный график

# Посмотрим продажи ПК с такими накопителями:
df_eda.groupby('SSD')['Price'].agg(['mean', 'median']).round(1)

"""Сводка SSD"""

# Сводка SSD
# Наибольший объем памяти:  2000, цена - 103753 рубля;
# Наименьший объем памяти:  1, цена - 84575 рубля;
# Медиана :  480.0, цена 68050 рубля;
# Средняя емкость носителя:  545.5;
# Асимметрия 0.855391;
# Эксцесс 0.957438.

"""# 2.2 Анализ категориальных переменных."""

df_eda.columns

cat = ['Country', 'title', 'sales', 'seller_rating', 'OS', 'Processor', 'TypeMemory', 'VideoCard', 'Price']

df_eda[cat][:5]

df_eda.shape

"""Country"""

# Country

df_eda['Country'].describe()

df_eda['Country'].unique()

df_eda['Country'].value_counts(dropna= False)

country = df_eda['Country'].value_counts().sort_values(ascending= True)

# Столбчатая диаграмма распределения по странам
plt.barh(country.index, country.values, color= 'g')
plt.title('Столбчатая диаграмма распределения стран')
plt.show()

# Построим круговую диаграмму
plt.pie(country, labels= country.index, autopct='%.1f', )
plt.show()

# Посмотрим, сколько по сборке из каких стран - составляют цены по средней и медиане:
df_eda.groupby('Country')['Price'].agg(['mean', 'median']).round(1)

"""Cводка Country"""

# Cводка Country
# Количество уникальных значений - 3 (nan не в счет);
# Доля стран сборки ПК:
# Россия - 88.9 %, цена - 58710 рублей;
# Китай - 10.8 %, цена 60829 рублей;
# Беларусь - 0.3%, цена 67672 рублей.

"""seller_rating"""

# seller_rating

df_eda['seller_rating'].describe()

# Количество уникальных значений.
df_eda['seller_rating'].nunique()

df_eda['seller_rating'].unique()

df_eda['seller_rating'].value_counts(dropna= False)

seller = df_eda['seller_rating'].value_counts().sort_values(ascending= True)

# Столбчатая диаграмма распределения по рейтингу.
plt.barh(seller.index, seller.values, color= 'g')
plt.title('Столбчатая диаграмма распределения стран')
plt.show()

# Столбчатая диаграмма малоинформативна ввиду того,
# что рейтинги представлены в вещественных числах (не дискретные значения), поэтому сливаются, плюс ко всему рейтинги представлены либо 0
# либо свыше 3,5.

# Выделим 5 основных значений рейтинга
seller_5 = df_eda['seller_rating'].value_counts()[:5]

# Построим круговую диаграмму по ТОП-5 рейтингов:
plt.pie(seller_5, labels= seller_5.index, autopct='%.1f')
plt.show()

"""Сводка seller_rating"""

df_eda.shape

# Посмотрим цены по рейтингам:
df_eda.groupby('seller_rating')['Price'].agg(['mean', 'median']).round(1)

# Количество уникальных значений признака - 17;
# медиана - 4,7, продажи по такому рейтингу 72095 рубля;
# Часто встречаемое значение рейтинга - 4.7, встречается 1576 раз (всего 3561 оценок);
# Рейтинг 4.7 - 53.2 %;
# 0.0 - 20.4 %, цена - 79870 рублей;
# 4.1 - 11.6 %, цена - 40975 рублей;
# 4.2 - 8.4 %, цена - 61476 рублей;
# 5.0 - 6.5 %, цена - 66948 рубля.

df_groupby = df_eda.groupby('seller_rating').agg(mean_=('Price', 'mean')).round(1); df_groupby

"""OS"""

# OS

# Статистики признака
df_eda['OS'].describe()

# Уникальных значений.
df_eda['OS'].unique()

df_eda['OS'].value_counts()

# Построим столбчатую диаграмму на основе 12 значений признака OS
os = df_eda['OS'].value_counts().sort_values(ascending= True)[-12:]
plt.barh(os.index, os.values, color= 'g')
plt.title('Столбчатая диаграмма распределения OS')
plt.show()

# Построим круговую диаграмму ТОП-5 OS:
os_5 = df_eda['OS'].value_counts()[:5]
plt.pie(os_5, labels= os_5.index, autopct='%.1f')
plt.show()

# Сводка по OS в разрезе цены:
df_eda.groupby('OS')['Price'].agg(['mean', 'median']).round(1)

"""Сводка OS"""

# Количество уникальных значений признака - 38;
# Самое встречаемое значение - Windows 10 Pro - 1753 единиц, цена - 72253 рубля;
# ТОП_5:
# Windows 10 Pro - 54.6 %
# Windows 11 Pro  - 20.8 %, цена - 75883 рубля;
# Windows 10 - 12.4 %, цена - 40019 рубля;
# windows пробная - 6.9 %, цена - 55355 рубля;
# Без OS - 5.3%, цена - 49900 рубля.

df_eda.columns

"""Processor"""

# Processor

# Статистики признака
df_eda['Processor'].describe()

# Количество уникальных значений
df_eda['Processor'].unique()

# Хит парад значений признака
df_eda['Processor'].value_counts()

# ТОП_5 значений признака
proc_5 = df_eda['Processor'].value_counts().sort_values(ascending= True)[-5:]

# Построим столбчатую диаграмму
plt.barh(proc_5.index, proc_5.values, color= 'g')
plt.title('Столбчатая диаграмма распределения по процессорам')
plt.show()

# Круговая диаграмма
plt.pie(proc_5, labels= proc_5.index, autopct='%.1f')
plt.show()

# Посмотрим каковы цены по каждому процессору в разрезе средней и медианы:
df_eda.groupby('Processor')['Price'].agg(['mean', 'median']).round(1)

"""Сводка Processor"""

# Количество уникальных значений - 58;
# Самое встречаемое значение Intel Core i5 - 1155 раз или 38.7 %, цена в среднем - 73034рубля;
# Intel Core i7 - 23.4 %, цена - 93463 рубля;
# Intel Core i3 - 17.4 %, цена 43673 рубля;
# AMD Ryzen 5 - 16.5 %, цена 59646 рубля;
# AMD Athlon - 4.1 %, цена - 35330 рубля.

"""TypeMemory"""

# TypeMemory

df_eda['TypeMemory'].describe()

df_eda['TypeMemory'].unique()

df_eda['TypeMemory'].value_counts()

# ТОП_4 значений признака TypeMemory
tm_4 = df_eda['TypeMemory'].value_counts().sort_values(ascending= True)[-4:]

# Построим столбчатую диаграмму TypeMemory
plt.barh(tm_4.index, tm_4.values, color= 'g')
plt.title('Столбчатая диаграмма по типам карт памяти')
plt.show()

# Построим круговую диаграмму по типам карт памяти
plt.figure(figsize= (8, 8))
plt.pie(tm_4, labels= tm_4.index, autopct='%.1f', )
plt.show()

# Посмотрим на цены в разрезе карт:
df_eda.groupby('TypeMemory')['Price'].agg(['mean', 'median']).round(1)

"""Сводка по TypeMemory"""

# Сводка по TypeMemory
# Количество уникальных значений 11;
# Часто встречаемое значение признака DDR4 - 3105 раз - 87.4 %, цена - 71143 рубля;
# DDR3 - 9.3 %, цена - 29474 рубля;
# не заполнено - 2.8 %, цена - 51674 рубля;
# DDR5 - 0.4 %, цена - 161098 рубля.

"""VideoCard"""

# VideoCard

# Статистики VideoCard
df_eda['VideoCard'].describe()

# Уникальные значения признака:
df_eda['VideoCard'].unique()

# Хит парад видеокарт:
df_eda['VideoCard'].value_counts()[:8]

# ТОП_8 значений признака VideoCard
vc_8 = df_eda['VideoCard'].value_counts().sort_values(ascending= True)[-8:]

# Построим столбчатую диаграмму по признаку VideoCard
plt.barh(vc_8.index, vc_8.values, color= 'g')
plt.title('Столбчатая диаграмма по типам Видеокарт')
plt.show()

# Построим круговую диаграмму по VideoCard (хоть и рекомендуют не больше 5,
# но здесь интересный случай - все 8 довольно релевантны!)
plt.figure(figsize= (7, 7))
plt.pie(vc_8, labels= vc_8.index, autopct='%.1f')
plt.show()

# Снимем ограничения по выводу на экран строк датафрейма:
# pd.set_option('display.max_rows', None)

# Сводник в разрезе цена ПК/видеокарта:
df_eda.groupby('VideoCard')['Price'].agg(['mean', 'median']).round(1)

"""Сводка VideoCard"""

# Сводка VideoCard

# Количество уникальных значений 81;

# Представлен следующими моделями (наиболее популярными):
# NVIDIA GeForce RTX 3060    604 - 24.3 %, цена ПК - 90713 рубля;
# NVIDIA GeForce RTX 3050    457 - 18.4 %, цена ПК - 77403 рубля;
# NVIDIA GeForce GTX 1650    327 - 13.2 %, цена ПК - 59134 рубля;
# NVIDIA GeForce GTX 1660    275 - 11.1 %, цена ПК - 66661 рубль;
# AMD Radeon Vega 7          212 - 8.5 %, цена ПК - 39690 рублей;
# Intel HD Graphics 2000     211 - 8.5 %, цена ПК - 24783 рубля;
# NVIDIA GeForce RTX 3070    200 - 8.1 %, цена ПК - 128044 рубля;
# NVIDIA GeForce GT 1030     197 - 7.9 %, цена ПК - 38240 рублей.

# title
df_eda['title'].describe()

# Количество уникальных значений признака:
df_eda['title'].nunique()

# очень большое значение уникальных названий ПК

# Хит парад значений признака:
df_eda['title'].value_counts()[:60]

# Выделяется 8 значений признака:
df_eda_title_8 = df_eda['title'].value_counts()[:8]; df_eda_title_8

tittle_8 = df_eda['title'].value_counts().sort_values(ascending= True)[-8:]

# Построим столбчатую диаграмму по признаку title
plt.barh(tittle_8.index, tittle_8.values, color= 'g')
plt.title('Столбчатая диаграмма по Названиям ПК')
plt.show()

# Ввиду того, что количество уникальных названий ПК - 1656, а также, что ТОП-8 - практически одинаковы по значениям,
# также имея ввиду то, что Заказчик исключает торговлю мини ПК, моноблоков и комплектующих - необходима фильтрация датасета:
# исключим эти элементы из нашего анализа.

# Проведем анализ товаров с аномально низкими ценами
# (на предмет - являются ли они все персональными компьютерами?).

filter = df_eda['Price'] < 12000
df_eda2 = df_eda[filter]

df_eda2

df_eda2.describe()

df_eda2['title'].value_counts(dropna= False)

df_eda.shape

# По цене (12 000) - мы обнаружили 20 единиц Мини ПК и Микрокомпьютеров:
#  удалим их из нашего анализа:
df_eda = df_eda[df_eda['Price'] > 12000]

df_eda.shape

# Начнем поиск Мини ПК, моноблоков и комплектующих с последующим удалением:
df_eda = df_eda[df_eda["title"].str.contains("Мини") == False ]

df_eda

df_eda.shape

# Удалили 66 строк содержащих Мини ПК

# Найдем и удалим моноблоки:
df_eda = df_eda[df_eda["title"].str.contains("моноблок") == False ]

df_eda.shape

# Нашли и удалили 7 записей содержащие "моноблок"

# Почистим индексы
df_eda.reset_index(drop=True, inplace= True)

# sales

df_eda['sales'].describe()

df_eda['sales'].unique()

df_eda['sales'].value_counts(dropna= False)

# выделяется восемь значений, в т.ч. - не занесенные в раздел по количеству продаж!
sal_8 = df_eda['sales'].value_counts().sort_values(ascending= True)[-7:]

# Построим барплот:
plt.barh(sal_8.index, sal_8.values, color= 'g')
plt.title('Количество продаж')
plt.show()

# Построим круговую диаграмму:
plt.pie(sal_8, labels= sal_8.index, autopct='%.1f')
plt.show();

# В общем графики ничего нового не показывают!

# Необходим анализ с ценами и названиями - чтобы понять хиты продаж и хиты комплектаций!

df_eda[['title', 'sales', 'Price']].sort_values(by= 'sales')

# Можно проанализировать оборот продаж по имеющимся данным о количестве продаж
# для этого необходимо 'sales' очищать и переводить в числовой формат:
df_eda['sales'].fillna(0, inplace= True)

df_eda['sales'].value_counts(dropna= False)

#df_eda['sales'] = df_eda['sales'].astype(str)

# Сделаем кодировку самого популярного элемента признака:
# "Купили менее 5 раз" - сделаем медианное значение между 1 и 5  - это 3
df_eda['sales'] = df['sales'].apply(lambda x: 'Купили более 3 раз' if x == 'Купили менее 5 раз' else x)

df_eda['sales'].value_counts(dropna= False)

df_eda['sales'].fillna(0, inplace= True)

df_eda['sales'] = df_eda['sales'].astype(str)

df_eda['Продажи'] = df_eda['sales'].apply(clean)

df_eda['Продажи'].value_counts(dropna= False)

df_eda['Продажи'] = df_eda['Продажи'].astype(int)

df_eda.info()

df_eda['Оборот'] = df_eda['Price'] * df_eda['Продажи']

obor_eda = df_eda.sort_values(by= 'Оборот', ascending= False)
obor_eda

df_eda.columns

top_eda = obor_eda[['Country', 'title', 'OS', 'Processor',
       'TypeMemory', 'VolumeMemory', 'VideoCard', 'Cores', 'HDD', 'SSD',
       'Price', 'Продажи', 'Оборот']]

"""Итоговая сводка по EDA"""

# Итоговая сводка по EDA (Доля в %, средние цены ПК при таких комплектующих):

# Country - Доля ПК по странам: Россия (88.9%), средняя цена ПК - 58710 р., Китай (10.8%) - 60829 р., Беларусь (0.3%) - 67672 р.;

# seller_rating представлен диапазоном от 0 до 5.0. Медиана значения - 4.7, продажа по такому рейтингу - 72095 р.;

# OS - выделяются три лидера:
# Windows 10 Pro - 1753 наблюдений (54.3%) - 72253 р.;
# Windows 11 Pro - 667 наблюдений (20.8%) - 75883 р.;
# Windows 10 - 398 наблюдений (12.4%) - 40019р.;

# Processor - выделяются три лидера:
# Intel Core i5 - 1155 наблюдений (38.7%) - средняя цена ПК 73034 р.;
# Intel Core i7 - 698 наблюдений (23,4%) - 93463 р.;
# Intel Core i3 - 519 наблюдений (17,4%) - 43673 р.;

# TypeMemory
# DDR4 - 3105 наблюдений (90.0 %) - средняя цена ПК 71143 р.;
# DDR3 - 332 наблюдения (9 %) - 29474 р.;
# все остальные в пределах 1 % доли;

# VolumeMemory - представлена в широком диапазоне от 1Гб -  до 64 Гб, медиана значения - 16 Гб;
# 16 Гб - 58,1 %, средняя цена ПК 66732 рубля;
# 32 Гб - 19,4%, - 96664 рубля;
# 8 Гб - 17,1%, - 43312 рубля;
# 4 Гб - 3,6%, - 26503 рубля
# 64 Гб - 1,9%, - 77044 рубля;

# VideoCard - достаточно разнообразный выбор, представлены в основной массе следующими моделями, плюс средними продажами ПК с такими видеокартами:
# NVIDIA GeForce RTX 3060    604 - 24.3 %, цена ПК - 90713 рубля;
# NVIDIA GeForce RTX 3050    457 - 18.4 %, цена ПК - 77403 рубля;
# NVIDIA GeForce GTX 1650    327 - 13.2 %, цена ПК - 59134 рубля;
# NVIDIA GeForce GTX 1660    275 - 11.1 %, цена ПК - 66661 рубль;
# AMD Radeon Vega 7          212 - 8.5 %, цена ПК - 39690 рублей;
# Intel HD Graphics 2000     211 - 8.5 %, цена ПК - 24783 рубля;
# NVIDIA GeForce RTX 3070    200 - 8.1 %, цена ПК - 128044 рубля;
# NVIDIA GeForce GT 1030     197 - 7.9 %, м - 38240 рублей.


# Cores - представлены в диапазоне от 4 до 12 ядер, медиана значения - 6 ядер;
# Наибольшее количество ядер:  24 - средняя цена ПК с такими ядрами 43417 рублей;
# Наименьшее количество ядер:  1 - цена 8001 рубля;
# Медиана :  6.0
# Среднее количество ядер:  7.0

# HDD - данный признак представлен всего лишь 1143 наблюдениями из 3561,
# для дальнейшего анализа (статистического) я не вижу смысла его использовать, представлен от 0 до 4000 Гб,
# медианное значение емкости такого диска составляет - 1000 Гб,
# При емкости 4000 Гб - цена 122490 р.

# SSD - представлен емкостями в диапазоне от 0 до 2000 Гб, медиана - 480 Гб и средняя емкость - 545 Гб,
# 2000 Гб - средняя цена ПК 103753 р.
# 1 Гб - 84575 р.;

# Price - весьма обширна от 5672 до 235900 рублей, медиана - 66405 рублей, средняя цена - 67061 рублей.

# ТОП_10 продаж ПК с комплектующими элементами:
top_eda[:10]

# Более детальный анализ по влиянию факторов (признаков представленных выше) на цену - будет
# выполнено в разделе Статистический анализ данных.

"""# 3. Статистический анализ данных"""

df_stat = df_eda.copy()

df_stat.info()

# Для статистического анализа возьмем 11 признаков:
col = ['Country', 'seller_rating', 'OS', 'Processor', 'TypeMemory',
       'VolumeMemory', 'VideoCard', 'Cores', 'SSD', 'Price', 'Продажи']

df_stat = df_stat[col]

df_stat.shape

# Где попарно вместе с целевым признаком будет выявлять статистическую значимость каждого из
# факторов, а также тесноту этой связи.

df_stat.head()

"""# 3.1 Анализ взаимосвязи числовых признаков."""

# Заменим <NA> на нули в признаке SSD:
df_stat['SSD'] = df_stat['SSD'].fillna(0)

# Проверку (числовых признаков) осуществим по методу Шапиро Уилка:
print(stats.shapiro(df_stat['Price']))
print(stats.shapiro(df_stat['VolumeMemory']))
print(stats.shapiro(df_stat['Cores']))
print(stats.shapiro(df_stat['SSD']))

# По всем числовым признакам - pvalue < 0.05 - отклоняем нулевую гипотезу о нормальном распределении.
# Поэтому будем попарно сравнивать факторы по критерию Манна Уитни

# Построим график PairGrid для всех числовых признаков:
d_p = ['seller_rating', 'VolumeMemory', 'Cores', 'SSD','Price']
g = sns.PairGrid(df_stat[d_p])
g.map(sns.scatterplot, alpha= 0.3);

# Взаимосвязи четко прослеживаются (все признаки с ценой имеют узкие диапазоны величин), для более удобного анализа построим гистограммы попарно с ценой.

"""Построим гистограммы и scatterplot всех числовых признаков"""

# Price
df_stat['Price'] = df_stat['Price'].astype(int)
df_stat['Price'].hist()

print(f"Максимальная: {df_stat['Price'].max()}")
print(f"Минимальная: {df_stat['Price'].min()}")
print(f"Средняя: {df_stat['Price'].mean()}")
print(f"Станд. отклонение: {df_stat['Price'].std()}")
print(f"Асимметрия: {df_stat['Price'].skew()}")
print(f"Эксцесс: {df_stat['Price'].kurtosis()}")

# Признак Price - имеет левостороннюю асимметрию, плосковершинную форму графика

"""VolumeMemory"""

# VolumeMemory
df_stat.plot('VolumeMemory', 'Price', kind= "scatter")

# График показывает узкие диапазоны величин признака VolumeMemory

df_stat['VolumeMemory'].hist(bins= 8);

print(f"Максимальная: {df_stat['VolumeMemory'].max()}")
print(f"Минимальная: {df_stat['VolumeMemory'].min()}")
print(f"Средняя: {df_stat['VolumeMemory'].mean()}")
print(f"Станд. отклонение: {df_stat['VolumeMemory'].std()}")
print(f"Асимметрия: {df_stat['VolumeMemory'].skew()}")
print(f"Эксцесс: {df_stat['VolumeMemory'].kurtosis()}")

# VolumeMemory - левосторонняя, плосковершинная форма

# Сравним признак VolumeMemory с Price  по критерию Манна Уитни:
stats.mannwhitneyu(df_stat['Price'], df_stat['VolumeMemory'])

# Связь признаков Price / VolumeMemory ЗНАЧИМА (тесноту это связи определим далее по коэффициенту  корреляции Пирсона/Спирмена)

"""Cores"""

# Cores
df_stat.plot('Cores', 'Price', kind= "scatter")

# Признак Cores также представлен в узких диапазонах, различных только по цене.

df_stat['Cores'].hist(bins= 8);

print(f"Максимальная: {df_stat['Cores'].max()}")
print(f"Минимальная: {df_stat['Cores'].min()}")
print(f"Средняя: {df_stat['Cores'].mean()}")
print(f"Станд. отклонение: {df_stat['Cores'].std()}")
print(f"Асимметрия: {df_stat['Cores'].skew()}")
print(f"Эксцесс: {df_stat['Cores'].kurtosis()}")

# Cores - левосторонняя, плосковершинная форма

# Сравним признак Cores с Price  по критерию Манна Уитни:
stats.mannwhitneyu(df_stat['Price'], df_stat['Cores'])

# Связь признаков Price / Cores ЗНАЧИМА (тесноту это связи определим далее по коэффициенту  корреляции Пирсона/Спирмена)

"""SSD"""

# SSD
df_stat.plot('SSD', 'Price', kind= "scatter")

# График SSD представлен в узких диапазонах, различных только по цене.

df_stat['SSD'] = df_stat['SSD'].astype(int)
df_stat['SSD'].hist(bins= 8);

print(f"Максимальная: {df_stat['SSD'].max()}")
print(f"Минимальная: {df_stat['SSD'].min()}")
print(f"Средняя: {df_stat['SSD'].mean()}")
print(f"Станд. отклонение: {df_stat['SSD'].std()}")
print(f"Асимметрия: {df_stat['SSD'].skew()}")
print(f"Эксцесс: {df_stat['SSD'].kurtosis()}")

# SSD - левосторонняя, плосковершинная форма

# Сравним признак SSD с Price  по критерию Манна Уитни:
stats.mannwhitneyu(df_stat['Price'], df_stat['SSD'])

# Связь признаков Price / SSD ЗНАЧИМА (тесноту это связи определим далее по коэффициенту  корреляции Пирсона/Спирмена)

df_stat.columns

"""Посчитаем корреляцию числовых признаков"""

# Все представленные признаки не являются распределенными нормально,
# поэтому применяем критерий Спирмена.

# Посчитаем корреляцию числовых признаков по методу Спирмена:
df_stat[['VolumeMemory', 'Cores', 'SSD', 'seller_rating', 'Price']].corr(method= 'spearman')

# тепловая карта
ran = ['seller_rating', 'VolumeMemory', 'Cores', 'SSD', 'Price']
hm = sns.heatmap(df_stat[ran].corr(method = 'spearman'), annot=True)

# Признак seller_rating - имеет отрицательную корреляцию с некоторыми признаками (Cores, SSD).

# Посмотрим насколько статистически значимы эти коэффициенты корреляции:

# seller_rating:
stats.spearmanr(df_stat.Price, df_stat.seller_rating)

# Данный признак не коррелирует с Price

# VolumeMemory:
stats.spearmanr(df_stat.Price, df_stat.VolumeMemory)

# Cores:
stats.spearmanr(df_stat.Price, df_stat.Cores)

# SSD:
stats.spearmanr(df_stat.Price, df_stat.SSD)

# Коэффициенты корреляции составили:
# seller_rating / Price - nan, статистическая связь НЕ ЗНАЧИМА;
# VolumeMemory / Price - 0.54 (Спирмен) - связь статистически ЗНАЧИМА;
# Cores / Price -  0.63 (Спирмен) - связь статистически ЗНАЧИМА;
# SSD / Price -  0.44 (Спирмен) - связь статистически ЗНАЧИМА.

# Можно рассмотреть также следующие пары:
# VolumeMemory / SSD
# Volumememory / Cores
# Cores / SSD

print(stats.spearmanr(df_stat.VolumeMemory, df_stat.SSD))
print(stats.spearmanr(df_stat.VolumeMemory, df_stat.Cores))
print(stats.spearmanr(df_stat.Cores, df_stat.SSD))

# Все коэффициенты лежат в пределах 0.37 - 0. 45- статистическая связь ЗНАЧИМА.
# ВСЕ ЭТИ ПРИЗНАКИ ЗНАЧИМЫ С ЦЕНОЙ И МЕЖДУ СОБОЙ!!!
# НЕОБХОДИМО ИХ АККУРАТНО ИСПОЛЬЗОВАТЬ ВМЕСТЕ - ИЗБЕГАЯ ЭФФЕКТА МУЛЬТИКОЛЛИНЕАРНОСТИ!!!

#df_stat.info()

df_stat.shape

"""# 3.2 Анализ взаимосвязи категориальных признаков"""

df_stat.columns

cat_s = ['Country', 'OS', 'Processor', 'TypeMemory', 'VideoCard', 'Продажи']

# Связь по критерию ХИ2 - критерий связи анализируемых показателей

# Построим таблицу сопряженности Продажи / Processor
WF = pd.crosstab(df_stat['Processor'], df_stat['Продажи']); WF

chi2, prob, f, expected = scipy.stats.chi2_contingency(WF)
output = "test Statistics: {}\ndegrees of freedom: {}\np-value: {}\nexpected: {}"

print(output.format( chi2, f, prob, expected))

# Критерий согласия Пирсона ХИ2 = p-value: 5.030442155616703e-30;
# Число степеней свободы - 768
# Отклоняем нулевую гипотезу о равенстве частот, pvalue меньше 0,05, связь статистически ЗНАЧИМА!

# Построим таблицу сопряженности Продажи / VideoCard
WF1 = pd.crosstab(df_stat['VideoCard'], df_stat['Продажи']); WF1

chi2, prob, f, expected = scipy.stats.chi2_contingency(WF1)
output = "test Statistics: {}\ndegrees of freedom: {}\np-value: {}\nexpected: {}"

print(output.format( chi2, f, prob, expected))

# Критерий согласия Пирсона ХИ2 = 3.3277958216108347e-184;
# Число степеней свободы - 1232;
# Отклоняем нулевую гипотезу о равенстве частот, pvalue меньше 0,05, связь Продажи / VideoCard статистически ЗНАЧИМА!

# Построим таблицу сопряженности Продажи / TypeMemory:
WF3 = pd.crosstab(df_stat['TypeMemory'], df_stat['Продажи']); WF3

chi2, prob, f, expected = scipy.stats.chi2_contingency(WF3)
output = "test Statistics: {}\ndegrees of freedom: {}\np-value: {}\nexpected: {}"

print(output.format( chi2, f, prob, expected))

# Критерий согласия Пирсона ХИ2 = 0.9994837428058355;
# Число степеней свобы - 128
# Отклоняем нулевую гипотезу о равенстве частот, pvalue больше 0,05, связь Продажи / VideoCard статистически НЕ ЗНАЧИМА!

"""# 3.3 Анализ взаимосвязи числовых и категориальных признаков"""

df_stat.columns

# Будем сравнивать числовые признаки: 'Cores', 'Price' с
# категоризированным 'Продажи'

df_stat.groupby('Cores')['Продажи'].mean()

f, ax = plt.subplots(figsize=(8, 8))
fig = sns.boxplot(x= 'Продажи', y= 'Cores', data= df_stat)

# График показывает, что продажи ПК по 50 включительно - находятся в диапазоне 5-6 ядер, продажи свыше 50
# это в основном 4 и 2 ядерные процессоры. Это и понятно, чем больше ядер - тем выше цена и ниже количество продаж.

# проверим на нормальность выбранные признаки:
print(stats.shapiro(df_stat['Cores']))
print(stats.shapiro(df_stat['Продажи']))

# Распределения данных признаков не является нормальным

# Сравним группы по критерию Манна-Уитни:
scipy.stats.mannwhitneyu(df_stat['Cores'],df_stat['Продажи'])

# Отклоняем нулевую гипотезу, различия статистически ЗНАЧИМЫ

"""Price / Продажи"""

df_stat.groupby('Продажи')['Price'].mean()

# если смотреть на общую тенденцию - видно, что количество продаж падают с увеличением цены!
# выше я уже отметил, что корреляция между этими признаками обратная и ЗНАЧИМА!

f, ax = plt.subplots(figsize=(8, 8))
fig = sns.boxplot(x= 'Продажи', y= 'Price', data= df_stat)

# Также отмечается: с увеличением цены - количество продаж уменьшается

# Сравним группы по критерию Манна-Уитни:
scipy.stats.mannwhitneyu(df_stat['Price'],df_stat['Продажи'])

# Отклоняем нулевую гипотезу, различия статистически ЗНАЧИМЫ

"""Сводка по корреляционному анализу"""

# Сводка по корреляционному анализу:

# Числовые признаки представлены следующими факторами:
# 'seller_rating', 'VolumeMemory', 'Cores', 'SSD', 'Price' (целевая переменная), sales (категориальный признак)

# По всем числовым признакам - pvalue < 0.05 - то есть распределение всех признаков не соответствует Нормальному распределению Гаусса.
# При попарном сравнении числовых признаков с целевым признаком корреляционная связь составила:

# seller_rating / Price - связь не обнаружена;

# VolumeMemory / Price - корреляция составила (по Спирмену) - 0.54, связь статистически ЗНАЧИМА;

# Cores / Price - корреляция (по Спирмену) - 0.63, связь статистически ЗНАЧИМА;

# SSD / Price - корреляция (по Спирмену) - 0.44, связь статистически ЗНАЧИМА;

# также обнаружена статистически ЗНАЧИМАЯ связь между признаками:
# # VolumeMemory / SSD - 0,37;
# Volumememory / Cores - 0,45 ;
# Cores / SSD - 0,4
# Коэффициент корреляции между этими признаками является статистически ЗНАЧИМЫМ.

# Корреляция по признакам Продажи / Цена - является отрицательной и составила - -0.21
# связь статистически ЗНАЧИМА!



# Рекомендации заказчику для комплектующих и цене (средняя):

# Средняя цена представленных ПК на рынке составляет - 67061 рубль;
# Все, что ниже этой цены - низкобюджетные (популярные) модели ПК (сборок);
# Цены свыше 83790 рублей (75-й процентиль) - являются дорогими, высокобюджетными;

# Страны, производящие сборки:
# Россия - 58710 р;
# Китай - 60829 р;

# Оперативная система, используемая в сборках ПК:
# Windows 10 Pro - 72253 р;
# Windows 11 Pro - 75883 р;
# Windows 10 - 40019 р;
# Либо без установки ОС - 49900 р;

# Процессор:
# Intel Core i5 - 73034 р;
# Intel Core i7 - 93463 р;
# Intel Core i3 - 43673 р;
# AMD Ryzen 5 - 59646 р;
# AMD Athlon - 35330 р;

# Количество ядер в процессоре:
# от 4 до 12;

# Тип оперативной памяти:
# DDR4 - 71143 р;
# DDR3 - 29474 р;
# DDR5 - для дорогих, высокобюджетных моделей - 161098 р;

# Объем оперативной памяти:
# 16 Гб - 66732 р;
# 32 Гб - 96664 р;
# 8 Гб - 43312 р;
# 4 Гб - 26507 р;
# 64 Гб - 77044 р;

# Видеокарта:
# NVIDIA GeForce RTX 3060    цена ПК - 90713 рубля;
# NVIDIA GeForce RTX 3050    цена ПК - 77403 рубля;
# NVIDIA GeForce GTX 1650    цена ПК - 59134 рубля;
# NVIDIA GeForce GTX 1660    цена ПК - 66661 рубль;
# AMD Radeon Vega 7          цена ПК - 39690 рублей;
# Intel HD Graphics 2000     цена ПК - 24783 рубля;
# NVIDIA GeForce RTX 3070    цена ПК - 128044 рубля;
# NVIDIA GeForce GT 1030     цена ПК - 38240 рублей.

# Емкость жесткого диска (HDD)- не менее 1000 Гб;

# Емкость твердотельного накопителя (SSD) - не менее 512 Гб 68050 р;

# Все сборки осуществлять из приведенных выше, в различных конфигурациях, - при этом ориентируясь
# на цену, чтобы попадать в тот или иной ценовой сегмент Покупателей.

# далее дам рекомендации исходя из фактических продаж и популярности ПК с комплектующими, а также с
# рекомендованными нижними и верхними границами цен (коридор цен):

# Поскольку, в течение года цена на ПК в среднем увеличилась на 20 % (относительно представленной здесь базы цен на ПК с комплектующими) - см. top_eda (ниже таблица),
# то цену (Price) - будем считать как базовую (с учетом наценки) - то есть средней розничной по рынку. Максимальную цену необходимо установить выше базовой на 10 %,
# минимальную цену - уменьшить на 25 %. Как показывает практика, цена ниже на 10 %,  чем у конкурентов - увеличивает оборот в полтора раза.
# Ниже представляю таблицу с минимальными, максимальными и базовыми ценами. А также в каких комплектациях представлены ПК.
# Таблица представлена в виде отфильтрованной по популярности (количеству продаж), то есть на вершине самые популярные сборки, идущие по убыванию.

# Произведем необходимый апгрейд таблицы:
top_eda.reset_index(drop= True, inplace= True)
top_eda['Базовая_цена'] = top_eda['Price']
top_eda['Мин_цена'] = top_eda['Price'] * 0.75
top_eda['Макс_цена'] = top_eda['Price'] * 1.1

top_eda.columns

top_eda[['Country', 'title', 'OS', 'Processor', 'TypeMemory', 'VolumeMemory',
       'VideoCard', 'Cores', 'HDD', 'SSD', 'Базовая_цена',
       'Мин_цена', 'Макс_цена', 'Продажи', 'Оборот']]

# Данная таблица представляется Заказчику.

top_eda.shape

